// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/ding-live/ding-golang/models/components"
	"net/http"
)

type FeedbackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	FeedbackResponse *components.FeedbackResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *FeedbackResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *FeedbackResponse) GetFeedbackResponse() *components.FeedbackResponse {
	if o == nil {
		return nil
	}
	return o.FeedbackResponse
}

func (o *FeedbackResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *FeedbackResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
