// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/ding-live/ding-golang/models/components"
	"net/http"
)

type RetryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Bad Request
	ErrorResponse *components.ErrorResponse
	// OK
	RetryAuthenticationResponse *components.RetryAuthenticationResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *RetryResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RetryResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *RetryResponse) GetRetryAuthenticationResponse() *components.RetryAuthenticationResponse {
	if o == nil {
		return nil
	}
	return o.RetryAuthenticationResponse
}

func (o *RetryResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RetryResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
