// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// Code - A machine-readable code that describes the error. Possible values are:
//   - `invalid_phone_number` - This is not a valid E.164 number.
//   - `internal_server_error` - An internal server error occurred.
//   - `bad_request` - The request was malformed.
//   - `account_invalid` - The provided customer UUID is invalid.
//   - `negative_balance` - You have a negative balance.
//   - `invalid_line` - Ding does not support this type of phone number.
//   - `unsupported_region` - Ding does not support this region yet.
//   - `invalid_auth_uuid` - The provided authentication UUID is invalid.
//   - `blocked_number` - The phone number is in the blocklist.
//   - `invalid_app_version` - The provided application version is invalid.
//   - `invalid_os_version` - The provided OS version is invalid.
//   - `invalid_device_model` - The provided device model is invalid.
//   - `invalid_device_id` - The provided device ID is invalid.
type Code string

const (
	CodeInvalidPhoneNumber            Code = "invalid_phone_number"
	CodeInternalServerError           Code = "internal_server_error"
	CodeBadRequest                    Code = "bad_request"
	CodeAccountInvalid                Code = "account_invalid"
	CodeNegativeBalance               Code = "negative_balance"
	CodeInvalidLine                   Code = "invalid_line"
	CodeUnsupportedRegion             Code = "unsupported_region"
	CodeInvalidAuthUUID               Code = "invalid_auth_uuid"
	CodeInvalidAppRealm               Code = "invalid_app_realm"
	CodeUnsupportedAppRealmDeviceType Code = "unsupported_app_realm_device_type"
	CodeAppRealmRequireDeviceType     Code = "app_realm_require_device_type"
	CodeBlockedNumber                 Code = "blocked_number"
	CodeInvalidAppVersion             Code = "invalid_app_version"
	CodeInvalidOsVersion              Code = "invalid_os_version"
	CodeInvalidDeviceModel            Code = "invalid_device_model"
	CodeInvalidDeviceID               Code = "invalid_device_id"
)

func (e Code) ToPointer() *Code {
	return &e
}

func (e *Code) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invalid_phone_number":
		fallthrough
	case "internal_server_error":
		fallthrough
	case "bad_request":
		fallthrough
	case "account_invalid":
		fallthrough
	case "negative_balance":
		fallthrough
	case "invalid_line":
		fallthrough
	case "unsupported_region":
		fallthrough
	case "invalid_auth_uuid":
		fallthrough
	case "invalid_app_realm":
		fallthrough
	case "unsupported_app_realm_device_type":
		fallthrough
	case "app_realm_require_device_type":
		fallthrough
	case "blocked_number":
		fallthrough
	case "invalid_app_version":
		fallthrough
	case "invalid_os_version":
		fallthrough
	case "invalid_device_model":
		fallthrough
	case "invalid_device_id":
		*e = Code(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Code: %v", v)
	}
}

// ErrorResponse - Bad Request
type ErrorResponse struct {
	// A machine-readable code that describes the error. Possible values are:
	//   * `invalid_phone_number` - This is not a valid E.164 number.
	//   * `internal_server_error` - An internal server error occurred.
	//   * `bad_request` - The request was malformed.
	//   * `account_invalid` - The provided customer UUID is invalid.
	//   * `negative_balance` - You have a negative balance.
	//   * `invalid_line` - Ding does not support this type of phone number.
	//   * `unsupported_region` - Ding does not support this region yet.
	//   * `invalid_auth_uuid` - The provided authentication UUID is invalid.
	//   * `blocked_number` - The phone number is in the blocklist.
	//   * `invalid_app_version` - The provided application version is invalid.
	//   * `invalid_os_version` - The provided OS version is invalid.
	//   * `invalid_device_model` - The provided device model is invalid.
	//   * `invalid_device_id` - The provided device ID is invalid.
	//
	Code *Code `json:"code,omitempty"`
	// A link to the documentation that describes the error.
	DocURL *string `json:"doc_url,omitempty"`
	// A human-readable message that describes the error.
	Message *string `json:"message,omitempty"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
