// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateCheckResponse struct {
	// The UUID of the corresponding authentication.
	AuthenticationUUID *string      `json:"authentication_uuid,omitempty"`
	Status             *CheckStatus `json:"status,omitempty"`
}

func (o *CreateCheckResponse) GetAuthenticationUUID() *string {
	if o == nil {
		return nil
	}
	return o.AuthenticationUUID
}

func (o *CreateCheckResponse) GetStatus() *CheckStatus {
	if o == nil {
		return nil
	}
	return o.Status
}
