// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateCheckRequest struct {
	// The authentication UUID that was returned when you created the authentication.
	AuthenticationUUID string `json:"authentication_uuid"`
	// The code that the user entered.
	CheckCode string `json:"check_code"`
	// Your customer UUID, which can be found in the API settings in the Dashboard.
	CustomerUUID string `json:"customer_uuid"`
}

func (o *CreateCheckRequest) GetAuthenticationUUID() string {
	if o == nil {
		return ""
	}
	return o.AuthenticationUUID
}

func (o *CreateCheckRequest) GetCheckCode() string {
	if o == nil {
		return ""
	}
	return o.CheckCode
}

func (o *CreateCheckRequest) GetCustomerUUID() string {
	if o == nil {
		return ""
	}
	return o.CustomerUUID
}
