// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/ding-live/ding-golang/models/sdkerrors"
)

type ErrorResponse struct {
	// A machine-readable code that describes the error.
	Code *sdkerrors.Code `json:"code,omitempty"`
	// A link to the documentation that describes the error.
	DocURL *string `json:"doc_url,omitempty"`
	// A human-readable message that describes the error.
	Message *string `json:"message,omitempty"`
}

func (o *ErrorResponse) GetCode() *sdkerrors.Code {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *ErrorResponse) GetDocURL() *string {
	if o == nil {
		return nil
	}
	return o.DocURL
}

func (o *ErrorResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
