// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// FeedbackRequestStatus - The type of the feedback.
type FeedbackRequestStatus string

const (
	FeedbackRequestStatusOnboarded    FeedbackRequestStatus = "onboarded"
	FeedbackRequestStatusNotOnboarded FeedbackRequestStatus = "not_onboarded"
)

func (e FeedbackRequestStatus) ToPointer() *FeedbackRequestStatus {
	return &e
}
func (e *FeedbackRequestStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "onboarded":
		fallthrough
	case "not_onboarded":
		*e = FeedbackRequestStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FeedbackRequestStatus: %v", v)
	}
}

type FeedbackRequest struct {
	// Your customer UUID, which can be found in the API settings in the dashboard.
	CustomerUUID string `json:"customer_uuid"`
	// An E.164 formatted phone number.
	PhoneNumber string `json:"phone_number"`
	// The type of the feedback.
	Status FeedbackRequestStatus `json:"status"`
}

func (o *FeedbackRequest) GetCustomerUUID() string {
	if o == nil {
		return ""
	}
	return o.CustomerUUID
}

func (o *FeedbackRequest) GetPhoneNumber() string {
	if o == nil {
		return ""
	}
	return o.PhoneNumber
}

func (o *FeedbackRequest) GetStatus() FeedbackRequestStatus {
	if o == nil {
		return FeedbackRequestStatus("")
	}
	return o.Status
}
