// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FeedbackResponse struct {
	// The UUID of the feedback.
	UUID *string `json:"uuid,omitempty"`
}

func (o *FeedbackResponse) GetUUID() *string {
	if o == nil {
		return nil
	}
	return o.UUID
}
