// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type LookupRequest struct {
	// An E.164 formatted phone number to lookup.
	PhoneNumber *string `json:"phone_number,omitempty"`
}

func (o *LookupRequest) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}
