// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RetryAuthenticationRequest struct {
	// The authentication UUID that was returned when you created the authentication.
	AuthenticationUUID string `json:"authentication_uuid"`
	// Your customer UUID, which can be found in the API settings in the dashboard.
	CustomerUUID string `json:"customer_uuid"`
}

func (o *RetryAuthenticationRequest) GetAuthenticationUUID() string {
	if o == nil {
		return ""
	}
	return o.AuthenticationUUID
}

func (o *RetryAuthenticationRequest) GetCustomerUUID() string {
	if o == nil {
		return ""
	}
	return o.CustomerUUID
}
