workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/ding-live/openapi/main/ding.yaml
        registry:
            location: registry.speakeasyapi.dev/ding/ding/my-source
targets:
    github.com/ding-live/ding-golang:
        target: go
        source: my-source
